travis:
  secure:
    BINSTAR_TOKEN: iN2BjE1G+iJZW1T0a+LTQWTkYLEAVh6khMLRW51EmYoEpKpCQpwarAf8yrX4SXLSjqgZ654TeIbXpyp8EZ+00OH0lr8i5M6Rxd5QBcWMgXljAgc2e0p8gJYD8W5c8xEjk89j19hJKni981dXkmyuN4zWs5XiZG1LuHayX8DXGtJ4Ps/5Vb4fudntBE7roP4jsC0zQaCSt4sbqeEW67X0MXfjT/DWVLTBvqYQ+aBGx/3yDrcBJWqnUDJd/fuPNNJEp2fSAO6cJ9FPm9HhXhqzNbPWJFhVvbjqADdhvXOkJ8oCYOY3hYiVwV3lg0N/YntrzYo72dgINRUmzosSsexSo9B1TuhgNIxXZH5GjpBZ1uMbqBqLpgras+eNDLtfDW0dWxj4t4B2rCDbWjVTTbDJ3i7++RaoMMcQRNXpu8ilEdJh4mf83VX7szNBm5sAYJgjnjvyzWRJ/G9CwdIskmj0PGH980/LaNW/M//PT20KAwX4vFg+JLzAquIs7Q64EuGgoTq+PwCPTX54cyhXelwZTEA5WaICPI8J40HC37TBW923hjBEHta2RJAEXlBP94CJle+cyOuODjy4oX4vcgG+/Dj3dSFUxa7ExPdjT4qFtbhxmDY40Qzli+f9UQpgFq67LpDPww8y+U4xYNlegAs5FIHrrzngfVp2rRU7yXB8vQE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
